// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRandomMove(arg1:number):Promise<any>;

export function GetValidPositions(arg1:number):Promise<Array<number>>;

export function Greet(arg1:string):Promise<string>;

export function ValidateMove(arg1:any,arg2:number):Promise<boolean>;
