// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateBoard() {
  return window['go']['main']['App']['GenerateBoard']();
}

export function GetBoard() {
  return window['go']['main']['App']['GetBoard']();
}

export function GetDefaultComplexity() {
  return window['go']['main']['App']['GetDefaultComplexity']();
}

export function GetDefaultMaxRuntime() {
  return window['go']['main']['App']['GetDefaultMaxRuntime']();
}

export function SetComplexity(arg1) {
  return window['go']['main']['App']['SetComplexity'](arg1);
}

export function SetMaxRuntime(arg1) {
  return window['go']['main']['App']['SetMaxRuntime'](arg1);
}

export function Solve() {
  return window['go']['main']['App']['Solve']();
}
