// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateBoard() {
  return window['go']['main']['App']['GenerateBoard']();
}

export function GetBoard() {
  return window['go']['main']['App']['GetBoard']();
}

export function GetRandomMove(arg1) {
  return window['go']['main']['App']['GetRandomMove'](arg1);
}

export function GetValidPositions(arg1) {
  return window['go']['main']['App']['GetValidPositions'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SetComplexity(arg1) {
  return window['go']['main']['App']['SetComplexity'](arg1);
}

export function SetMaxRuntime(arg1) {
  return window['go']['main']['App']['SetMaxRuntime'](arg1);
}

export function Solve() {
  return window['go']['main']['App']['Solve']();
}

export function ValidateMove(arg1, arg2) {
  return window['go']['main']['App']['ValidateMove'](arg1, arg2);
}
