// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateBoard():Promise<any>;

export function GetBoard():Promise<any>;

export function GetDefaultComplexity():Promise<number>;

export function GetDefaultMaxRuntime():Promise<number>;

export function SetComplexity(arg1:number):Promise<void>;

export function SetMaxRuntime(arg1:number):Promise<void>;

export function Solve():Promise<main.SolveResult>;
