name: Test and coverage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
      - uses: actions/setup-node@v2
        with:
          go-version: '1.18'
      - name: Run coverage
        run: 
          cd frontend && npm install && npm run build && cd .. &&   go test -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
