name: Release the newest version

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            {
              name: 15GoFast-linux-amd,
              platform: linux/amd64,
              os: ubuntu-latest,
              sign: "false",
            },
            {
              name: 15GoFast-windows,
              platform: windows/amd64,
              os: windows-latest,
              sign: "false",
            },
            {
              name: 15GoFast-darwin,
              platform: darwin/universal,
              os: macos-latest,
              sign: "false",
            },
          ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: dAppServer/wails-build-action@v2
        with:
          go-version: 1.18
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          sign: ${{matrix.build.sign}}
          sign-macos-installer-id: "DONT TRY TO SIGN!"
          package: "false"

      # Upload build assets
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.build.name}}
          path: |
            */bin/
            *\bin\*
            */bin/*.app/Contents/MacOS/

  release:
    name: "Release"
    needs: build
    runs-on: "ubuntu-latest"

    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            */bin/*
            */bin/*.app/Contents/MacOS/*
            *\bin\*
